# Generated by Django 4.2.5 on 2023-09-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0002_remove_aluno_nome_aluno_user_alter_aluno_sexo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['user__first_name'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('Outro', 'Outro'), ('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=30, null=True),
        ),
    ]
